In [23]:
#PART 1!
#Function that reads the text file and turns it into a vertical database
def readFile(file_name):
    text_file = open(file_name, "r")
    lines = text_file.readlines()
    #print(lines)
    possible_entries = set()
    data_list = []
    #Converts each line from the text file into a set and unionizes them
    #Also creates a list of lists of data from the text file
    count = 1
    for i in lines:
        row_data = i.strip().split()
        possible_entries = possible_entries.union(set(row_data))
        data_list.append((count, row_data))
        count = count + 1

    #Converts the set back into list
    possible_entries = list(possible_entries)

    #Creates a list of tuples in the form (possible entry, set of row numbers the entry occurs in)
    end_data = []
    for j in range(len(possible_entries)):
        record_set = set()
        for k in range(len(data_list)):
            if possible_entries[j] in data_list[k][1]:
                record_set.add(data_list[k][0])
        entry_set = {possible_entries[j]}
        tuple=[entry_set, record_set]
        end_data.append(tuple)
    
    #Sorts the end result by the first entry in each tuple
    end_data.sort()

    #Closes the text file
    text_file.close()

    return end_data

P = readFile("example.txt")
print(P)

[[{'D'}, {1, 3, 5, 6}], [{'A'}, {1, 3, 4, 5}], [{'B'}, {1, 2, 3, 4, 5, 6}], [{'E'}, {1, 2, 3, 4, 5}], [{'C'}, {2, 4, 5, 6}]]


In [20]:
#PART 1!
#P is the set of potential itemsets
#minsup is the minimum support
#C is the set of closed itemsets
#Algorithm CHARM (9.2)
def charm(P, minsup, C):
    #STEP 1
    P.sort(key=lambda item: len(item[1]))
    #STEP 2
    for i, [X_i, tX_i] in enumerate(P):
        #STEP 3
        P_i = []
        #STEP 4
        for j, [X_j, tX_j] in enumerate(P):
            if j>i:
                #STEP 5
                X_ij = set(X_i).union(set(X_j))
                #STEP 6
                tX_ij = tX_i.intersection(tX_j)
                #STEP 7
                if len(tX_ij) >= minsup:
                    #STEP 8
                    if tX_i == tX_j:
                        #STEP 9
                        for k in range(len(P_i)):
                            if set(X_i).issubset(P_i[k][0]):
                                P_i[k][0] = P_i[k][0].union(X_ij)
                        P[i][0] = X_ij
                        X_i = X_ij
                        #STEP 10
                        P.pop(j)
                    #STEP 11 & 12
                    elif tX_i.issubset(tX_j):
                        #STEP 13
                        for k in range(len(P_i)):
                            if set(X_i).issubset(P_i[k][0]):
                                P_i[k][0] = P_i[k][0].union(X_ij)
                        P[i][0] = X_ij
                        X_i = X_ij
                    #STEP 14
                    else:
                        #STEP 15
                        P_i.append([X_ij, tX_ij])
        #STEP 16
        if P_i != []:
            charm(P_i, minsup, C)
        #STEP 17
        if not any(set(X_i).issubset(Z) and tX_i == t_z for Z, t_z in C) and len(tX_i)>=minsup:
            #STEP 18
            C.append([set(X_i), tX_i])

In [21]:
#PART 1
#Example.txt
P = readFile("example.txt")
minsup = 3
C = []
closed_itemsets = charm(P, minsup, C)

#Printing in the desired output method

for i in C:
    new_list = []
    for j in i[0]:
        new_list.append(j)
    new_list.sort()
    for j in new_list:
        print(j, end=" ")
    print("-", len(i[1]))
print("Number of closed itemsets:", len(C))

A B D E - 3
B D - 4
A B E - 4
B C E - 3
B C - 4
B E - 5
B - 6
Number of closed itemsets: 7


In [24]:
#PART 1
#Chess.txt
P = readFile("chess.txt")
minsup = 3000
C = []
charm(P, minsup, C)

#Printing in the desired output method

for i in C:
    new_list = []
    for j in i[0]:
        new_list.append(j)
    new_list.sort()
    for j in new_list:
        print(j, end=" ")
    print("-", len(i[1]))

print("Number of closed itemsets:", len(C))

48 52 58 - 3001
48 52 - 3002
48 58 - 3012
48 - 3013
29 52 56 58 - 3000
29 52 56 - 3001
29 56 58 - 3005
29 56 - 3006
52 56 58 - 3015
52 56 - 3016
56 58 - 3020
56 - 3021
29 52 58 60 66 - 3001
29 52 60 66 - 3002
52 58 60 66 - 3009
52 60 66 - 3010
29 58 60 66 - 3012
29 60 66 - 3013
58 60 66 - 3020
60 66 - 3021
29 34 40 52 58 - 3003
29 34 40 52 - 3004
34 40 52 58 - 3007
34 40 52 - 3008
29 34 40 58 - 3012
29 34 40 - 3013
34 40 58 - 3016
34 40 - 3017
29 34 52 58 - 3026
29 34 52 - 3027
34 52 58 - 3030
34 52 - 3031
29 34 58 - 3035
29 34 - 3036
34 58 - 3039
34 - 3040
29 58 60 62 - 3001
52 58 60 62 - 3003
58 60 62 - 3014
29 40 52 58 62 - 3019
29 40 58 62 - 3030
40 52 58 62 - 3034
40 58 62 - 3045
29 52 58 62 - 3034
29 58 62 - 3045
52 58 62 - 3049
58 62 - 3060
40 58 60 7 - 3005
40 60 7 - 3006
29 52 58 60 7 - 3012
29 52 60 7 - 3013
52 58 60 7 - 3019
52 60 7 - 3020
29 58 60 7 - 3023
29 60 7 - 3024
58 60 7 - 3030
60 7 - 3031
29 40 52 58 7 - 3031
29 40 52 7 - 3032
40 52 58 7 - 3038
40 52 7 - 3039
29 40

In [60]:
#PART 2
import numpy as np
from sklearn import datasets
from sklearn.metrics import normalized_mutual_info_score #CSCI 4390 students instructed to use
from scipy.stats import multivariate_normal #Instructed to use
from scipy.special import logsumexp #Instructed to use

#Loading in the iris dataset
iris = datasets.load_iris()
X = iris.data[:, :4]  #Take only the first four features.
y_true = iris.target

#Initialization of variables (STEPS 1 through 4)
k = 3  #Number of clusters which we are given
epsilon = 1e-4  #Convergence threshold

#Expectation-Maximization (EM) Algorithm
def EM_algorithm(X, k, epsilon):
    #STEPS 1-4
    log_likelihood_old = -np.inf
    n, d = X.shape
    means = X[np.random.choice(n, k, replace=False)] 
    covariances = [np.cov(X.T) + 1e-6*np.eye(d) for _ in range(k)]
    priors = [1./k] * k 
    #STEP 5 and 13 (the for loop)
    for _ in range(100): #Limiting run to 100 iterations

        #Calculating log probabilities and responsibilities
        log_probs = np.zeros((X.shape[0], k))
        for i in range(k):
            log_probs[:, i] = multivariate_normal.logpdf(X, mean=means[i], cov=covariances[i], allow_singular=True) + np.log(priors[i])
        
        #Expectation Step (steps 7-8) 
        log_responsibilities = log_probs - logsumexp(log_probs, axis=1)[:, np.newaxis]
        responsibilities = np.exp(log_responsibilities)

        #Maximation Step (steps 9-12) 
        Nk = responsibilities.sum(axis=0)
        means = np.dot(responsibilities.T, X) / Nk[:, np.newaxis]
        covariances = []
        for i in range(k):
            diff = X - means[i]
            covariances.append(np.dot(responsibilities[:, i] * diff.T, diff) / Nk[i] + 1e-6*np.eye(d))
        priors = Nk / n
        
        #Checking for convergence - this is also tied to step 5 and 13
        log_likelihood_new = np.sum(logsumexp(log_probs, axis=1))
        if np.abs(log_likelihood_new - log_likelihood_old) < epsilon:
            break
        log_likelihood_old = log_likelihood_new
    
    return responsibilities, means, covariances

#Instructed to run code several times due to different random initial center
#selections and report clustering with the best NMI score
nmi_scores = []
for iteration in range(3): 
    #Calls EM_algorithm function
    responsibilities, means, covariances = EM_algorithm(X, k, epsilon)

    #Assigns points to clusters
    cluster_sizes = responsibilities.argmax(axis=1)

    #Calculates the NMI score
    nmi_score = normalized_mutual_info_score(y_true, cluster_sizes)

    print("CLUSTERS ITERATION "+str(iteration+1)+":\n")

    #Printing the mean vectors
    for i in range(len(means)):
        print("Mean vector for cluster "+str(i+1)+":")
        print(means[i], "\n")

    #Printing the covariance matrices
    for i in range(len(covariances)):
        print("Covariance matrix for cluster "+str(i+1)+":")
        print(covariances[i], "\n")

    #Printing the cluster sizes
    cluster_sizes = np.bincount(cluster_sizes)
    for i in range(len(cluster_sizes)):
        print("Cluster size of cluster "+str(i+1)+":", cluster_sizes[i])
    print("")

    #Printing nmi score and adding it to list of nmi scores:
    print("Normalized Mutual Information (NMI) score:", nmi_score, "\n")
    nmi_scores.append(nmi_score)

#Printing highest nmi score
highest_score = 0
highest_index = 0
for score in range(len(nmi_scores)):
    if nmi_scores[score] > highest_score:
        highest_score = nmi_scores[score]
        highest_index = score+1
print("Highest NMI score is:", highest_score)
print("This score comes from cluster iteration:", highest_index)


CLUSTERS ITERATION 1:

Mean vector for cluster 1:
[6.3837782  2.99296378 5.34337839 2.1082539 ] 

Mean vector for cluster 2:
[6.19789516 2.80844629 4.67604281 1.44896384] 

Mean vector for cluster 3:
[5.00606855 3.42815279 1.46202186 0.24599253] 

Covariance matrix for cluster 1:
[[0.2740157  0.0771115  0.16167022 0.06977794]
 [0.0771115  0.0733673  0.06659267 0.04266233]
 [0.16167022 0.06659267 0.16799269 0.0738163 ]
 [0.06977794 0.04266233 0.0738163  0.05852009]] 

Covariance matrix for cluster 2:
[[0.5078188  0.13222468 0.55747113 0.17377599]
 [0.13222468 0.11694764 0.13842983 0.05661952]
 [0.55747113 0.13842983 0.78875599 0.2461764 ]
 [0.17377599 0.05661952 0.2461764  0.09222552]] 

Covariance matrix for cluster 3:
[[0.12174686 0.0971679  0.01601907 0.01012907]
 [0.0971679  0.14066379 0.01144081 0.00912148]
 [0.01601907 0.01144081 0.02955745 0.00594997]
 [0.01012907 0.00912148 0.00594997 0.01088603]] 

Cluster size of cluster 1: 35
Cluster size of cluster 2: 65
Cluster size of clus

In [45]:
#PART 2
import numpy as np
from sklearn import datasets
from sklearn.metrics import normalized_mutual_info_score #CSCI 4390 students instructed to use
from scipy.stats import multivariate_normal #Instructed to use
from scipy.special import logsumexp #Instructed to use

#Loading in the iris dataset
iris = datasets.load_iris()
X = iris.data[:, :4]  #Take only the first four features.
y_true = iris.target

#Initialization of variables (STEPS 1 through 4)
np.random.seed(42)
k = 3  #Number of clusters which we are given
n, d = X.shape
means = X[np.random.choice(n, k, replace=False)] 
covariances = [np.cov(X.T) + 1e-6*np.eye(d) for _ in range(k)]
priors = [1./k] * k 

#Function used in calculating log probabilities - needed for the expectation step
def log_probabilities(X, means, covariances, priors):
    log_probs = np.zeros((X.shape[0], k))
    for i in range(k):
        log_probs[:, i] = multivariate_normal.logpdf(X, mean=means[i], cov=covariances[i], allow_singular=True) + np.log(priors[i])
    return log_probs

#em_step function holds the bulk of the EM algorithm. It conducts code for steps 7-8
#(The expectation step) and steps 9-12 (the Maximization step)
def em_step(X, log_probs):
    #Expectation Step
    log_responsibilities = log_probs - logsumexp(log_probs, axis=1)[:, np.newaxis]
    responsibilities = np.exp(log_responsibilities)

    #Maximation Step
    Nk = responsibilities.sum(axis=0)
    means = np.dot(responsibilities.T, X) / Nk[:, np.newaxis]
    covariances = []
    for i in range(k):
        diff = X - means[i]
        covariances.append(np.dot(responsibilities[:, i] * diff.T, diff) / Nk[i] + 1e-6*np.eye(d))
    priors = Nk / n

    return means, covariances, priors, responsibilities

#Expectation-Maximization (EM) Algorithm
epsilon = 1e-4  #Convergence threshold
log_likelihood_old = -np.inf

#STEP 5 & 13 are the for loop
for _ in range(100): #Limiting run to 100 iterations

    #Calls both functions to execute most of the algorithm
    log_probs = log_probabilities(X, means, covariances, priors)
    means, covariances, priors, responsibilities = em_step(X, log_probs)
    
    #Checking for convergence through use of the em_step function
    log_likelihood_new = np.sum(logsumexp(log_probs, axis=1))
    if np.abs(log_likelihood_new - log_likelihood_old) < epsilon:
        break
    log_likelihood_old = log_likelihood_new

#Assigns points to clusters
cluster_sizes = responsibilities.argmax(axis=1)

#Calculates the NMI score
nmi_score = normalized_mutual_info_score(y_true, cluster_sizes)

#Printing the mean vectors
for i in range(len(means)):
    print("Mean vector for cluster "+str(i+1)+":")
    print(means[i], "\n")

#Printing the covariance matrices
for i in range(len(covariances)):
    print("Covariance matrix for cluster "+str(i+1)+":")
    print(covariances[i], "\n")

#Printing the cluster sizes
cluster_sizes = np.bincount(cluster_sizes)
for i in range(len(cluster_sizes)):
    print("Cluster size of cluster "+str(i+1)+":", cluster_sizes[i])
print("")

#Printing nmi score:
print("Normalized Mutual Information (NMI) score:", nmi_score)


Mean vector for cluster 1:
[5.91502764 2.77784905 4.20167391 1.29701385] 

Mean vector for cluster 2:
[5.006 3.428 1.462 0.246] 

Mean vector for cluster 3:
[6.54462467 2.94869021 5.47970545 1.98470136] 

Covariance matrix for cluster 1:
[[0.27532156 0.09692814 0.18467993 0.0544    ]
 [0.09692814 0.09264368 0.09113793 0.0429968 ]
 [0.18467993 0.09113793 0.20067764 0.06099848]
 [0.0544     0.0429968  0.06099848 0.03200769]] 

Covariance matrix for cluster 2:
[[0.121765 0.097232 0.016028 0.010124]
 [0.097232 0.140817 0.011464 0.009112]
 [0.016028 0.011464 0.029557 0.005948]
 [0.010124 0.009112 0.005948 0.010885]] 

Covariance matrix for cluster 3:
[[0.38704763 0.09220756 0.3027853  0.06161675]
 [0.09220756 0.11034069 0.08427016 0.05600105]
 [0.3027853  0.08427016 0.32771693 0.07446077]
 [0.06161675 0.05600105 0.07446077 0.08576136]] 

Cluster size of cluster 1: 45
Cluster size of cluster 2: 50
Cluster size of cluster 3: 55

Normalized Mutual Information (NMI) score: 0.8996935451597475
